### ISSUE TITLE
how to run the exe on ubuntu 

### ISSUE THREAD

**Issue by luhaiyong** [jsuarezruiz/forms-embedding-gtk#1]
hi ,this project forms-embedding-gtk ,i rebuild use vs2017 on windows os,and running successful .
but i want to run this exe on ubuntu，i use mono command, failed!
plz help \me ,how to use mono build and run this project on Ubuntn ! 
,

**Comment by jsuarezruiz** [comment]
You should be able to compile with MonoDevelop or compile from Windows or macOS and copy the Output. From Linux you should use the _"mono App.exe"_ command.
